# This is a basic workflow to help you get started with Actions

name: generate-dat-file

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: bash $GITHUB_WORKSPACE/script.sh
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "google ip data"
          prerelease: false
          files: |
            data/*
            output/dat/*
